#!/bin/zsh
npm -g install npm
npm -g install babel-cli
npm -g install babel-eslint
npm -g install babel-node-debug
npm -g install babel-preset-es2015
npm -g install bower
npm -g install brunch
npm -g install bunyan
npm -g install coffee-script
npm -g install dash-cli
npm -g install electron-prebuilt
npm -g install elm-oracle
npm -g install elm-test
npm -g install eslint
npm -g install eslint-config-airbnb
npm -g install eslint-config-standard
npm -g install eslint-plugin-ava
npm -g install eslint-plugin flowtype
npm -g install eslint-plugin-jsx-a11y
npm -g install eslint-plugin-babel
npm -g install eslint-plugin-immutable
npm -g install eslint-plugin-import
npm -g install eslint-plugin-react
npm -g install estraverse
npm -g install estraverse-fb
npm -g install flow-typed
npm -g install foreman
npm -g install gatsby
npm -g install generator-craft
npm -g install generator-keystone
npm -g install gifify
npm -g install gist-cli
npm -g install gitbook-cli
npm -g install greenkeeper
npm -g install growl
npm -g install grunt-cli
npm -g install gulp
npm -g install hexo
npm -g install hexo-cli
npm -g install hogan
npm -g install http-server
npm -g install ijavascript
npm -g install pug
npm -g install javascripting
npm -g install js-beautify
npm -g install json-server
npm -g install jsonlint
npm -g install karma-cli
npm -g install learnyounode
npm -g install live-server
npm -g install localtunnel
npm -g install lodash-cli
npm -g install local-npm
npm -g install marked
npm -g install mocha
npm -g install mediumcli
npm -g install node-inspector
npm -g install node-libs-browser
npm -g install node-static
npm -g install npmlist
npm -g install npmrc
npm -g install npm-check-updates
npm -g install package-json-validator
npm -g install pagespeed-cli
npm -g install phantomjs-prebuild
npm -g install plato
npm -g install pm2
npm -g install pushstate-server
npm -g install replpad
npm -g install rwb
npm -g install secretkey
npm -g install selenium-standalone
npm -g install slow-deps
npm -g install surge
npm -g install swagger
npm -g install standard
npm -g install tern
npm -g install tinypng
npm -g install tslint
npm -g install typescript
npm -g install typings
npm -g install uncss
npm -g install watchify
npm -g install webpack
npm -g install webpack-dev-server
npm -g install yo
