#!/bin/zsh
npm -g install babel-cli
npm -g install babel-node-debug
npm -g install bunyan
npm -g install dash-cli
npm -g install foreman
npm -g install gifify
npm -g install gist-cli
npm -g install http-server
npm -g install ijavascript
npm -g install json-server
npm -g install jsonlint
npm -g install karma-cli
npm -g install live-server
npm -g install localtunnel
npm -g install lodash-cli
npm -g install marked
npm -g install mocha
npm -g install mediumcli
npm -g install node-inspector
npm -g install npmlist
npm -g install npmrc
npm -g install package-json-validator
npm -g install pagespeed-cli
npm -g install plato
npm -g install pm2
npm -g install pushstate-server
npm -g install replpad
npm -g install secretkey
npm -g install selenium-standalone
npm -g install slow-deps
npm -g install swagger
npm -g install tern
npm -g install tinypng
npm -g install tslint
npm -g install typescript
npm -g install uncss
