#!/bin/zsh
npm install -g @commitlint/cli
npm install -g @commitlint/config-conventional
npm install -g babel-cli
npm install -g conventional-changelog-cli@4.1.0
npm install -g corepack
npm install -g dash-cli
npm install -g foreman
npm install -g gifify
npm install -g gist-cli
npm install -g http-server
npm install -g ijavascript
npm install -g ipt
npm install -g json-server
npm install -g jsonlint
npm install -g live-server-https
npm install -g live-server
npm install -g localtunnel
npm install -g marked
npm install -g netlify-cli
npm install -g npm-check-updates
npm install -g npm-check
npm install -g npmlist
npm install -g npmrc
npm install -g package-json-validator
npm install -g pagespeed-cli
npm install -g pm2
npm install -g pushstate-server
npm install -g secretkey
npm install -g shapefile
npm install -g slow-deps
npm install -g snyk
npm install -g stylelint
npm install -g svgo
npm install -g topojson-client
npm install -g topojson-server
npm install -g trash-cli
npm install -g typescript
npm install -g uncss
