#!/bin/zsh
npm -g install @commitlint/cli 
npm -g install @commitlint/config-conventional
npm -g install @mermaid-js/mermaid-cli
npm -g install babel-cli
npm -g install babel-node-debug
npm -g install conventional-changelog-cli
npm -g install dash-cli
npm -g install foreman
npm -g install gifify
npm -g install gist-cli
npm -g install http-server
npm -g install ijavascript
npm -g install ipt
npm -g install json-server
npm -g install jsonlint
npm -g install live-server
npm -g install live-server-https
npm -g install localtunnel
npm -g install marked
npm -g install netlify-cli
npm -g install npm-check-updates
npm -g install npmlist
npm -g install npmrc
npm -g install package-json-validator
npm -g install pagespeed-cli
npm -g install pm2
npm -g install pushstate-server
npm -g install secretkey
npm -g install shapefile
npm -g install slow-deps
npm -g install snyk
npm -g install stylelint
npm -g install svgo
npm -g install topojson-client
npm -g install topojson-server
npm -g install toposjson-simplify
npm -g install typescript
npm -g install trash-cli
npm -g install uncss
