call pathogen#helptags()
call pathogen#runtime_append_all_bundles()

syntax on
filetype plugin indent on

set nocompatible

set tabstop=2
set smarttab
set shiftwidth=2
set autoindent
set expandtab

set backup
set backupdir=~/.vim/backups
set history=100
set ruler
set incsearch
set hlsearch
set number
